server:
  port: 8083

spring:
  application:
    name: campaign-service
  datasource:
    url: jdbc:mysql://localhost:3306/campaigns_db
    username: root
    password: Harish@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
